name: envcheck
on:
  push:
    paths:
      - 'envcheck/**'
      - '.github/workflows/envcheck.yml'
    branches:
      - main

jobs:
  build:
    name: envcheck-build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envcheck
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Build
        run: make
